/**
 * TypeEditor - A visual editor for Python type annotations
 * 
 * Creates an interactive editor for building and editing Python type annotations
 * with support for base types (int, float, str, bool) and container types 
 * (list, tuple, set, dict).
 * 
 * This was mostly generated by AI, with guidance and tweaks by Jeffrey Bush.
 * 
 * @example
 * // Basic usage
 * const editor = new TypeEditor(document.getElementById('editor'));
 * 
 * @example
 * // With change callback
 * const editor = new TypeEditor(document.getElementById('editor'), {
 *     onChange: (typeString) => {
 *         console.log('Type changed:', typeString);
 *         document.getElementById('output').textContent = typeString;
 *     }
 * });
 * 
 * @example
 * // With initial type
 * const editor = new TypeEditor(document.getElementById('editor'), {
 *     initialType: 'list[tuple[int, str]]'
 * });
 * 
 * @example
 * // With custom allowed types
 * const editor = new TypeEditor(document.getElementById('editor'), {
 *     allowedTypes: ['int', 'str', 'list', 'dict']
 * });
 * 
 * @example
 * // Getting the current type
 * const currentType = editor.getTypeString();
 * console.log(currentType); // e.g., "list[tuple[int, str]]"
 * 
 * @example
 * // Setting from a string
 * try {
 *     editor.setTypeString('dict[str, int]');
 * } catch (error) {
 *     console.error('Parse error:', error.message);
 * }
 * 
 * @example
 * // Resetting the editor
 * editor.clear();
 */
class TypeEditor {
    /**
     * Creates a new TypeEditor instance
     * 
     * @param {HTMLElement} element - The DOM element where the editor will be mounted.
     *                                 The class 'type-editor' will be added to this element.
     * @param {Object} [options={}] - Configuration options
     * @param {function(string):void} [options.onChange] - Callback function that will be called 
     *                                                      whenever the type changes. Receives the 
     *                                                      new type string as a parameter.
     * @param {string[]} [options.allowedTypes] - Array of allowed type names. If not provided,
     *                                             defaults to ['int', 'float', 'str', 'bool', 
     *                                             'list', 'tuple', 'set', 'dict'].
     * @param {string} [options.initialType] - Initial type string to parse and display. If not 
     *                                          provided, defaults to the first available type.
     * 
     * @example
     * // Simple initialization
     * const editor = new TypeEditor(document.getElementById('my-editor'));
     * 
     * @example
     * // With callback
     * const editor = new TypeEditor(document.getElementById('my-editor'), {
     *     onChange: (typeString) => {
     *         console.log('New type:', typeString);
     *     }
     * });
     * 
     * @example
     * // With custom allowed types
     * const editor = new TypeEditor(document.getElementById('my-editor'), {
     *     allowedTypes: ['int', 'str', 'list', 'dict']
     * });
     * 
     * @example
     * // With initial type
     * const editor = new TypeEditor(document.getElementById('my-editor'), {
     *     initialType: 'list[tuple[int, str]]'
     * });
     * 
     * @example
     * // With all options
     * const editor = new TypeEditor(document.getElementById('my-editor'), {
     *     onChange: (typeString) => console.log(typeString),
     *     allowedTypes: ['int', 'str', 'list'],
     *     initialType: 'list[int]'
     * });
     */
    // Private fields
    #element;
    #typeId;
    #onChangeCallback;
    #baseTypes;
    #containerTypes;
    #allTypes;

    constructor(element, options = {}) {
        this.#element = element;
        this.#element.classList.add('type-editor');
        this.#typeId = 0;
        this.#onChangeCallback = options.onChange || null;
        
        // Default types
        const defaultBaseTypes = ['int', 'float', 'str', 'bool'];
        const defaultContainerTypes = ['list', 'tuple', 'set', 'dict'];
        const defaultAllTypes = [...defaultBaseTypes, ...defaultContainerTypes];
        
        if (options.allowedTypes) {
            this.#allTypes = [...options.allowedTypes];
            this.#baseTypes = options.allowedTypes.filter(t => defaultBaseTypes.includes(t));
            this.#containerTypes = options.allowedTypes.filter(t => defaultContainerTypes.includes(t));
        } else {
            this.#baseTypes = defaultBaseTypes;
            this.#containerTypes = defaultContainerTypes;
            this.#allTypes = defaultAllTypes;
        }
        
        // Initialize with initial type or default
        if (options.initialType) {
            try {
                this.setTypeString(options.initialType);
            } catch (error) {
                // If initial type fails to parse, fall back to default
                console.warn('Failed to parse initialType:', error.message);
                this.clear();
            }
        } else {
            this.clear();
        }
    }
    
    /**
     * Gets the current type as a Python string
     * 
     * Returns a Python annotation string representation of the currently
     * constructed type. For example "list[int]" or "tuple[int, str, float]".
     * 
     * @returns {string} The current type as a string, or empty string if no type is set
     * 
     * @example
     * const typeString = editor.getTypeString();
     * console.log(typeString); // "list[int]"
     * 
     * @example
     * // Complex nested type
     * const typeString = editor.getTypeString();
     * console.log(typeString); // "dict[str, int]"
     */
    getTypeString() {
        const rootContainer = this.#element.querySelector('.type-container');
        if (rootContainer) {
            return this.#generateTypeString(rootContainer);
        }
        return '';
    }
    
    /**
     * Checks if the current type is valid (no placeholders selected)
     * 
     * Returns true if all type dropdowns have valid types selected,
     * false if any dropdown has the placeholder "type" option selected.
     * 
     * @returns {boolean} True if the type is valid, false if any placeholder is selected
     * 
     * @example
     * if (editor.isValid()) {
     *     const typeString = editor.getTypeString();
     *     console.log('Valid type:', typeString);
     * } else {
     *     console.log('Please select all types');
     * }
     */
    isValid() {
        const allSelects = this.#element.querySelectorAll('.type-container select');
        for (const select of allSelects) {
            if (!select.value || select.value === '') {
                return false;
            }
            
            // If custom is selected, check that the input has a valid custom type name
            if (select.value === 'custom') {
                const container = select.closest('.type-container');
                const customInput = container.querySelector('.custom-type-input');
                if (!customInput || !this.#isValidCustomTypeName(customInput.value)) {
                    return false;
                }
            }
        }
        return true;
    }
    
    /**
     * Parses and sets the editor from a type string
     * 
     * Parses a Python type string and rebuilds the editor to match.
     * Supports multiple syntax variations for convenience, including
     * bare container type names.
     * 
     * @param {string} typeStr - The type string to parse. Must be a valid type expression
     *                           in Python format (e.g., "list[int]", "tuple[int, str]")
     * 
     * @throws {Error} If the type string cannot be parsed
     * 
     * @example
     * // Simple type
     * editor.setTypeString('list[int]');
     * 
     * @example
     * // Bare container types (uses default nested type)
     * editor.setTypeString('list');   // becomes "list[int]"
     * editor.setTypeString('tuple');  // becomes "tuple[int]"
     * editor.setTypeString('set');    // becomes "set[int]"
     * editor.setTypeString('dict');   // becomes "dict[str, int]"
     * 
     * @example
     * // Nested container types
     * editor.setTypeString('list[tuple[int, str]]');
     * 
     * @example
     * // Dict with various syntaxes
     * editor.setTypeString('dict[str, int]');
     * editor.setTypeString('dict[int, str]');
     * editor.setTypeString('dict[int, str]');
     * editor.setTypeString('dict[list[int]]');  // assumes str keys
     * 
     * @example
     * // With error handling
     * try {
     *     editor.setTypeString('invalid type string');
     * } catch (error) {
     *     console.error('Failed to parse:', error.message);
     * }
     * 
     * @example
     * // Complex nested types with parentheses
     * editor.setTypeString('tuple[list[int], str, set[float]]');
     */
    setTypeString(typeStr) {
        try {
            const parsed = this.#parseTypeString(typeStr);
            this.#element.innerHTML = '';
            this.#typeId = 0;
            this.#buildTypeFromParsed(parsed, this.#element);
            this.#notifyChange();
        } catch (error) {
            throw new Error('Error parsing type string: ' + error.message);
        }
    }
    
    /**
     * Clears the editor and resets to initial state
     * 
     * Removes all type selections and resets the editor to show
     * a single type dropdown with placeholder selected. Triggers the onChange callback if set.
     * 
     * @example
     * editor.clear();
     * 
     * @example
     * // Clear and check type string
     * editor.clear();
     * console.log(editor.getTypeString()); // "?" (placeholder selected, no type chosen)
     */
    clear() {
        this.#element.innerHTML = '';
        this.#typeId = 0;
        this.#createTypeDropdown(this.#element, true);
    }
    
    // Private: Notify of changes
    #notifyChange() {
        if (this.#onChangeCallback) {
            this.#onChangeCallback(this.getTypeString());
        }
    }

    // Private: Check if a string is a valid custom type name
    #isValidCustomTypeName(name) {
        if (!name || typeof name !== 'string') {
            return false;
        }
        const trimmed = name.trim();
        // Must match identifier pattern: [a-zA-Z][a-zA-Z0-9_]*
        const identifierPattern = /^[a-zA-Z][a-zA-Z0-9_.|,[\]() ]*$/;
        if (!identifierPattern.test(trimmed)) {
            return false;
        }
        // Must not be in allTypes (not a built-in type)
        return !this.#allTypes.includes(trimmed);
    }

    // Private: Check if we need immutable types only (inside set or dict keys)
    #needsImmutableTypes(element) {
        let current = element;
        while (current) {
            if (current.classList && current.classList.contains('type-container')) {
                const select = current.querySelector(':scope > select');
                if (select && select.value === 'set') {
                    return true;
                }
                if (select && select.value === 'dict') {
                    // Check if we're in the keys section of a dict
                    let checkElement = element;
                    while (checkElement && checkElement !== current) {
                        if (checkElement.classList && checkElement.classList.contains('indented-nested')) {
                            const label = checkElement.querySelector('.dict-label');
                            if (label && label.textContent === 'keys of') {
                                return true;
                            }
                        }
                        checkElement = checkElement.parentElement;
                    }
                }
                // Also check if inside a tuple that's inside a restricted context
                if (select && select.value === 'tuple') {
                    current = current.parentElement;
                    continue;
                }
            }
            current = current.parentElement;
        }
        return false;
    }

    // Private: Backward compatibility wrapper
    #isInsideSet(element) {
        return this.#needsImmutableTypes(element);
    }

    #createTypeDropdown(parent, isRoot = false) {
        const container = document.createElement('span');
        container.className = 'type-container';
        const id = this.#typeId++;
        container.dataset.id = id;

        const select = document.createElement('select');

        // Add placeholder option first
        const placeholderOption = document.createElement('option');
        placeholderOption.value = '';
        placeholderOption.textContent = 'type';
        select.appendChild(placeholderOption);

        // Determine which types to show based on context
        const inSetContext = this.#isInsideSet(parent);
        const immutableTypes = [...this.#baseTypes, 'tuple'];
        const typesToShow = inSetContext ? immutableTypes : this.#allTypes;

        // Add type options
        typesToShow.forEach(type => {
            const option = document.createElement('option');
            option.value = type;
            option.textContent = type;
            select.appendChild(option);
        });

        // Default to placeholder (empty value)
        select.selectedIndex = 0;

        select.addEventListener('change', (e) => {
            // Only handle change if a valid type is selected
            if (e.target.value) {
                this.#handleTypeChange(e, container, id);
            } else {
                // Clear nested elements if placeholder is selected
                const childElements = container.querySelectorAll('.type-container:not(:first-child), .mode-select, .connector, .add-type-btn, .remove-type-btn, .indented-nested, .dict-label, .dict-connector');
                childElements.forEach(el => el.remove());
                this.#notifyChange();
            }
        });
        
        container.appendChild(select);
        parent.appendChild(container);
        
        return container;
    }

    #handleTypeChange(event, container, id) {
        const selectedType = event.target.value;
        
        // Remove any existing nested elements
        const childElements = container.querySelectorAll('.type-container:not(:first-child), .mode-select, .connector, .add-type-btn, .remove-type-btn, .indented-nested, .dict-label, .dict-connector, .custom-type-input');
        childElements.forEach(el => el.remove());

        if (selectedType === 'custom') {
            this.#addCustomInput(container);
        } else if (this.#containerTypes.includes(selectedType)) {
            if (selectedType === 'list') {
                this.#addContainerInterface(container, 'of'); // List defaults to 'of'
            } else if (selectedType === 'set') {
                this.#addSetInterface(container);
            } else if (selectedType === 'tuple') {
                this.#addContainerInterface(container, 'with'); // Tuple defaults to 'with'
            } else if (selectedType === 'dict') {
                this.#addDictInterface(container);
            }
        }
        
        this.#notifyChange();
    }
    
    #addCustomInput(container) {
        const input = document.createElement('input');
        input.type = 'text';
        input.className = 'custom-type-input';
        input.placeholder = 'Enter custom type';
        input.addEventListener('input', () => {
            this.#notifyChange();
        });
        container.appendChild(input);
    }

    #addSetInterface(container) {
        // Set only supports 'of' mode, show 'of' label
        const connector = document.createElement('span');
        connector.className = 'connector';
        connector.textContent = 'of';
        container.appendChild(connector);
        
        // Wrap nested type in indented container
        const nestedWrapper = document.createElement('div');
        nestedWrapper.className = 'indented-nested';
        container.appendChild(nestedWrapper);
        
        this.#createTypeDropdown(nestedWrapper);
    }

    #addDictInterface(container) {
        // Dict always uses 'with'
        const connector = document.createElement('span');
        connector.className = 'connector';
        connector.textContent = 'with';
        container.appendChild(connector);
        
        // Keys section
        const keysWrapper = document.createElement('div');
        keysWrapper.className = 'indented-nested';
        container.appendChild(keysWrapper);
        
        const keysLabel = document.createElement('span');
        keysLabel.className = 'dict-label';
        keysLabel.textContent = 'keys of';
        keysWrapper.appendChild(keysLabel);
        
        this.#createTypeDropdown(keysWrapper);
        
        // "associated with" on its own line
        const associatedWith = document.createElement('div');
        associatedWith.className = 'dict-connector';
        associatedWith.textContent = 'associated with';
        container.appendChild(associatedWith);
        
        // Values section
        const valuesWrapper = document.createElement('div');
        valuesWrapper.className = 'indented-nested';
        container.appendChild(valuesWrapper);
        
        const valuesLabel = document.createElement('span');
        valuesLabel.className = 'dict-label';
        valuesLabel.textContent = 'values of';
        valuesWrapper.appendChild(valuesLabel);
        
        this.#createTypeDropdown(valuesWrapper);
    }

    #addContainerInterface(container, defaultMode) {
        // Create dropdown for "of" vs "with"
        const modeSelect = document.createElement('select');
        modeSelect.className = 'mode-select';

        const ofOption = document.createElement('option');
        ofOption.value = 'of';
        ofOption.textContent = 'of';
        ofOption.title = 'Contains an arbitrary number of elements, all of the same type';
        modeSelect.appendChild(ofOption);

        const withOption = document.createElement('option');
        withOption.value = 'with';
        withOption.textContent = 'with';
        withOption.title = 'Contains a fixed number of elements, each of a possiblydifferent type';
        modeSelect.appendChild(withOption);

        // Set default
        modeSelect.value = defaultMode;

        container.appendChild(modeSelect);

        // Add change listener
        modeSelect.addEventListener('change', (e) => {
            this.#updateContainerMode(container, e.target.value);
            this.#updateModeWarning(container, this.#getContainerType(container), e.target.value);
        });

        // Initialize with default mode
        this.#updateContainerMode(container, defaultMode);
        this.#updateModeWarning(container, this.#getContainerType(container), defaultMode);
    }

    #updateContainerMode(container, mode) {
        // Remove existing type dropdowns, buttons, and nested wrappers after mode selection
        const existingTypes = container.querySelectorAll('.type-container:not(:first-child)');
        const existingButtons = container.querySelectorAll('.add-type-btn, .remove-type-btn');
        const existingWrappers = container.querySelectorAll('.indented-nested');
        existingTypes.forEach(el => el.remove());
        existingButtons.forEach(el => el.remove());
        existingWrappers.forEach(el => el.remove());

        if (mode === 'of') {
            // Single type dropdown in indented wrapper
            const nestedWrapper = document.createElement('div');
            nestedWrapper.className = 'indented-nested';
            container.appendChild(nestedWrapper);
            
            this.#createTypeDropdown(nestedWrapper);
        } else {
            // Multiple type dropdowns with add/remove buttons, all at same indent.
            // "with" starts with at least two entries.
            this.#addWithType(container, true);
            this.#addWithType(container, false);
        }
        
        this.#notifyChange();
    }

    #getContainerType(container) {
        const typeSelect = container.querySelector(':scope > select');
        return typeSelect ? typeSelect.value : '';
    }

    #updateModeWarning(container, selectedType, mode) {
        const existingWarning = container.querySelector('.mode-warning');
        if (existingWarning) {
            existingWarning.remove();
        }

        let warningText = '';
        if (selectedType === 'tuple' && mode === 'of') {
            warningText = '"tuple with" is preferred since it has a fixed number of elements';
        } else if (selectedType === 'list' && mode === 'with') {
            warningText = '"list of" is preferred since it has a variable number of elements';
        }

        if (!warningText) {
            return;
        }

        const warning = document.createElement('div');
        warning.className = 'mode-warning';
        warning.textContent = warningText;
        container.appendChild(warning);
    }

    #addWithType(container, isFirst = false) {
        // Create indented wrapper for each type in "with" mode
        const itemWrapper = document.createElement('div');
        itemWrapper.className = 'indented-nested';
        container.appendChild(itemWrapper);
        
        // Add buttons at the front of the line
        const buttonContainer = document.createElement('span');
        buttonContainer.className = 'nested-leader-container';
        itemWrapper.appendChild(buttonContainer);

        // Add "+" button
        const addBtn = document.createElement('button');
        addBtn.className = 'add-type-btn';
        addBtn.textContent = '+';
        addBtn.addEventListener('click', () => {
            this.#addWithType(container, false);
            this.#updateWithButtonStates(container);
        });
        buttonContainer.appendChild(addBtn);

        // Add remove button (always present)
        const removeBtn = document.createElement('button');
        removeBtn.className = 'remove-type-btn';
        removeBtn.textContent = '−';
        removeBtn.addEventListener('click', () => {
            const nestedWrappers = Array.from(container.children).filter(child =>
                child.classList && child.classList.contains('indented-nested')
            );
            if (nestedWrappers.length <= 2) {
                return;
            }
            // Remove the entire wrapper
            itemWrapper.remove();
            this.#updateWithButtonStates(container);
            this.#notifyChange();
        });
        buttonContainer.appendChild(removeBtn);

        // Add the type dropdown after buttons
        const typeContainer = this.#createTypeDropdown(itemWrapper);

        // Update button states after adding
        this.#updateWithButtonStates(container);

        return typeContainer;
    }

    #updateWithButtonStates(container) {
        // Count how many "with" items exist
        const nestedWrappers = Array.from(container.children).filter(child => 
            child.classList && child.classList.contains('indented-nested')
        );
        
        // Enable/disable remove buttons based on count
        nestedWrappers.forEach(wrapper => {
            const removeBtn = wrapper.querySelector('.remove-type-btn');
            if (removeBtn) {
                removeBtn.disabled = nestedWrappers.length <= 2;
            }
        });
    }

    #generateTypeString(container) {
        const select = container.querySelector('select');
        const selectedType = select.value;
        
        if (!selectedType) {
            return '?';
        }

        if (selectedType === 'custom') {
            const customInput = container.querySelector('.custom-type-input');
            if (customInput && this.#isValidCustomTypeName(customInput.value)) {
                return customInput.value.trim();
            }
            return '?';
        }

        if (this.#baseTypes.includes(selectedType)) {
            return selectedType;
        }

        if (selectedType === 'set') {
            const nestedWrapper = container.querySelector('.indented-nested');
            if (nestedWrapper) {
                const nestedContainer = nestedWrapper.querySelector('.type-container');
                if (nestedContainer) {
                    const nestedType = this.#generateTypeString(nestedContainer);
                    return `set[${nestedType}]`;
                }
            }
            return 'set[?]';
        }

        if (selectedType === 'dict') {
            const nestedWrappers = Array.from(container.children).filter(child => 
                child.classList && child.classList.contains('indented-nested')
            );
            
            let keyType = '?';
            let valueType = '?';
            
            nestedWrappers.forEach(wrapper => {
                const label = wrapper.querySelector('.dict-label');
                const typeContainer = wrapper.querySelector('.type-container');
                
                if (label && typeContainer) {
                    const typeString = this.#generateTypeString(typeContainer);
                    if (label.textContent === 'keys of') {
                        keyType = typeString;
                    } else if (label.textContent === 'values of') {
                        valueType = typeString;
                    }
                }
            });

            return `dict[${keyType}, ${valueType}]`;
        }

        if (selectedType === 'list' || selectedType === 'tuple') {
            const modeSelect = container.querySelector('.mode-select');
            const mode = modeSelect ? modeSelect.value : 'of';

            if (mode === 'of') {
                const nestedWrapper = container.querySelector('.indented-nested');
                if (nestedWrapper) {
                    const nestedContainer = nestedWrapper.querySelector('.type-container');
                    if (nestedContainer) {
                        const nestedType = this.#generateTypeString(nestedContainer);
                        if (selectedType === 'tuple') {
                            return `tuple[${nestedType}, ...]`;
                        }
                        return `${selectedType}[${nestedType}]`;
                    }
                }
                if (selectedType === 'tuple') {
                    return 'tuple[?, ...]';
                }
                return `${selectedType}[?]`;
            } else {
                const nestedWrappers = Array.from(container.children).filter(child => 
                    child.classList && child.classList.contains('indented-nested')
                );
                
                if (nestedWrappers.length > 0) {
                    const types = nestedWrappers.map(wrapper => {
                        const typeContainer = wrapper.querySelector('.type-container');
                        if (!typeContainer) return '?';
                        return this.#generateTypeString(typeContainer);
                    });
                    return `${selectedType}[${types.join(', ')}]`;
                }
                return `${selectedType}[?]`;
            }
        }

        return selectedType;
    }

    // Private: Parser functions
    #parseTypeString(typeStr) {
        typeStr = (typeStr || '').trim();

        if (typeStr === '?' || typeStr === '') {
            return { type: '' };
        }

        const splitTopLevelCommas = (text) => {
            const parts = [];
            let current = '';
            let depthBracket = 0;
            let depthParen = 0;
            for (let i = 0; i < text.length; i++) {
                const ch = text[i];
                if (ch === '[') depthBracket++;
                else if (ch === ']') depthBracket--;
                else if (ch === '(') depthParen++;
                else if (ch === ')') depthParen--;

                if (ch === ',' && depthBracket === 0 && depthParen === 0) {
                    parts.push(current.trim());
                    current = '';
                } else {
                    current += ch;
                }
            }
            if (current.trim()) { parts.push(current.trim()); }
            return parts;
        };

        const findOuterGeneric = (text) => {
            const firstBracket = text.indexOf('[');
            if (firstBracket === -1) {
                return { base: text.trim(), inner: null };
            }
            if (!text.endsWith(']')) {
                throw new Error(`Invalid generic type: ${text}`);
            }
            let depth = 0;
            for (let i = firstBracket; i < text.length; i++) {
                if (text[i] === '[') depth++;
                else if (text[i] === ']') depth--;
                if (depth === 0 && i !== text.length - 1) {
                    throw new Error(`Invalid generic type: ${text}`);
                }
            }
            if (depth !== 0) {
                throw new Error(`Unmatched brackets in type: ${text}`);
            }
            return {
                base: text.slice(0, firstBracket).trim(),
                inner: text.slice(firstBracket + 1, -1).trim()
            };
        };

        const parsePython = (text) => {
            const { base, inner } = findOuterGeneric(text.trim());

            if (inner == null) {
                if (this.#baseTypes.includes(base)) {
                    return { type: base };
                }
                if (base === 'list') {
                    return { type: 'list', mode: 'of', nested: { type: '' } };
                }
                if (base === 'set') {
                    return { type: 'set', mode: 'of', nested: { type: '' } };
                }
                if (base === 'tuple') {
                    return { type: 'tuple', mode: 'with', types: [{ type: '' }, { type: '' }] };
                }
                if (base === 'dict') {
                    return { type: 'dict', keyType: { type: '' }, valueType: { type: '' } };
                }

                if (this.#allTypes.includes('custom') && (this.#isValidCustomTypeName(base) || base === 'custom')) {
                    return {
                        type: 'custom',
                        customValue: base === 'custom' ? '' : base
                    };
                }

                throw new Error(`Unknown type: ${base}`);
            }

            const args = splitTopLevelCommas(inner);

            if (base === 'list') {
                if (args.length <= 1) {
                    return {
                        type: 'list',
                        mode: 'of',
                        nested: args.length === 1 ? parsePython(args[0]) : { type: '' }
                    };
                }
                return {
                    type: 'list',
                    mode: 'with',
                    types: args.map(parsePython)
                };
            }

            if (base === 'set') {
                return {
                    type: 'set',
                    mode: 'of',
                    nested: args.length ? parsePython(args[0]) : { type: '' }
                };
            }

            if (base === 'tuple') {
                if (args.length === 2 && args[1] === '...') {
                    return {
                        type: 'tuple',
                        mode: 'of',
                        nested: parsePython(args[0])
                    };
                }
                return {
                    type: 'tuple',
                    mode: 'with',
                    types: args.length ? args.map(parsePython) : [{ type: '' }, { type: '' }]
                };
            }

            if (base === 'dict') {
                return {
                    type: 'dict',
                    keyType: args[0] ? parsePython(args[0]) : { type: '' },
                    valueType: args[1] ? parsePython(args[1]) : { type: '' }
                };
            }

            throw new Error(`Unsupported generic type: ${base}`);
        };

        return parsePython(typeStr);
    }

    #buildTypeFromParsed(parsed, parentElement) {
        const container = document.createElement('span');
        container.className = 'type-container';
        const id = this.#typeId++;
        container.dataset.id = id;

        const select = document.createElement('select');
        
        // Add placeholder option first
        const placeholderOption = document.createElement('option');
        placeholderOption.value = '';
        placeholderOption.textContent = 'type';
        select.appendChild(placeholderOption);
        
        // Determine which types to show based on context
        const inSetContext = this.#isInsideSet(parentElement);
        const immutableTypes = [...this.#baseTypes, 'tuple'];
        const typesToShow = inSetContext ? immutableTypes : this.#allTypes;

        typesToShow.forEach(type => {
            const option = document.createElement('option');
            option.value = type;
            option.textContent = type;
            select.appendChild(option);
        });

        select.value = parsed.type;
        
        // Add change event listener so dropdowns work after parsing
        select.addEventListener('change', (e) => {
            // Only handle change if a valid type is selected
            if (e.target.value) {
                this.#handleTypeChange(e, container, id);
            } else {
                // Clear nested elements if placeholder is selected
                const childElements = container.querySelectorAll('.type-container:not(:first-child), .mode-select, .connector, .add-type-btn, .remove-type-btn, .indented-nested, .dict-label, .dict-connector, .custom-type-input');
                childElements.forEach(el => el.remove());
                this.#notifyChange();
            }
        });
        
        container.appendChild(select);
        parentElement.appendChild(container);

        // Handle custom type
        if (parsed.type === 'custom') {
            this.#addCustomInput(container);
            const customInput = container.querySelector('.custom-type-input');
            if (customInput && parsed.customValue) {
                customInput.value = parsed.customValue;
            }
        }
        // Handle container-specific setup
        else if (parsed.type === 'set') {
            const connector = document.createElement('span');
            connector.className = 'connector';
            connector.textContent = 'of';
            container.appendChild(connector);
            
            const nestedWrapper = document.createElement('div');
            nestedWrapper.className = 'indented-nested';
            container.appendChild(nestedWrapper);
            
            this.#buildTypeFromParsed(parsed.nested, nestedWrapper);
        } else if (parsed.type === 'dict') {
            const connector = document.createElement('span');
            connector.className = 'connector';
            connector.textContent = 'with';
            container.appendChild(connector);
            
            // Keys section
            const keysWrapper = document.createElement('div');
            keysWrapper.className = 'indented-nested';
            container.appendChild(keysWrapper);
            
            const keysLabel = document.createElement('span');
            keysLabel.className = 'dict-label';
            keysLabel.textContent = 'keys of';
            keysWrapper.appendChild(keysLabel);
            
            this.#buildTypeFromParsed(parsed.keyType, keysWrapper);
            
            // "associated with" on its own line
            const associatedWith = document.createElement('div');
            associatedWith.className = 'dict-connector';
            associatedWith.textContent = 'associated with';
            container.appendChild(associatedWith);
            
            // Values section
            const valuesWrapper = document.createElement('div');
            valuesWrapper.className = 'indented-nested';
            container.appendChild(valuesWrapper);
            
            const valuesLabel = document.createElement('span');
            valuesLabel.className = 'dict-label';
            valuesLabel.textContent = 'values of';
            valuesWrapper.appendChild(valuesLabel);
            
            this.#buildTypeFromParsed(parsed.valueType, valuesWrapper);
        } else if (parsed.type === 'list' || parsed.type === 'tuple') {
            const modeSelect = document.createElement('select');
            modeSelect.className = 'mode-select';

            const ofOption = document.createElement('option');
            ofOption.value = 'of';
            ofOption.textContent = 'of';
            ofOption.title = 'Contains an arbitrary number of elements, all of the same type';
            modeSelect.appendChild(ofOption);

            const withOption = document.createElement('option');
            withOption.value = 'with';
            withOption.textContent = 'with';
            withOption.title = 'Contains a fixed number of elements, each of a possiblydifferent type';
            modeSelect.appendChild(withOption);

            modeSelect.value = parsed.mode;
            
            // Add change event listener so mode selection works after parsing
            modeSelect.addEventListener('change', (e) => {
                this.#updateContainerMode(container, e.target.value);
                this.#updateModeWarning(container, this.#getContainerType(container), e.target.value);
            });
            
            container.appendChild(modeSelect);
            this.#updateModeWarning(container, parsed.type, parsed.mode);

            if (parsed.mode === 'of') {
                const nestedWrapper = document.createElement('div');
                nestedWrapper.className = 'indented-nested';
                container.appendChild(nestedWrapper);
                
                this.#buildTypeFromParsed(parsed.nested, nestedWrapper);
            } else {
                // "with" mode
                const withTypes = parsed.types.length >= 2
                    ? parsed.types
                    : [...parsed.types, ...Array(2 - parsed.types.length).fill({ type: '' })];

                withTypes.forEach((typeObj) => {
                    const itemWrapper = document.createElement('div');
                    itemWrapper.className = 'indented-nested';
                    container.appendChild(itemWrapper);
                    
                    const buttonContainer = document.createElement('span');
                    buttonContainer.className = 'nested-leader-container';
                    itemWrapper.appendChild(buttonContainer);

                    const addBtn = document.createElement('button');
                    addBtn.className = 'add-type-btn';
                    addBtn.textContent = '+';
                    addBtn.addEventListener('click', () => {
                        this.#addWithType(container, false);
                        this.#updateWithButtonStates(container);
                    });
                    buttonContainer.appendChild(addBtn);

                    const removeBtn = document.createElement('button');
                    removeBtn.className = 'remove-type-btn';
                    removeBtn.textContent = '−';
                    removeBtn.addEventListener('click', () => {
                        const nestedWrappers = Array.from(container.children).filter(child =>
                            child.classList && child.classList.contains('indented-nested')
                        );
                        if (nestedWrappers.length <= 2) {
                            return;
                        }
                        itemWrapper.remove();
                        this.#updateWithButtonStates(container);
                        this.#notifyChange();
                    });
                    buttonContainer.appendChild(removeBtn);

                    this.#buildTypeFromParsed(typeObj, itemWrapper);
                });
                
                this.#updateWithButtonStates(container);
            }
        }

        return container;
    }
}

// Export the TypeEditor class
export default TypeEditor;
